#!/bin/bash

## Description: Apply eslint to the Sillage theme.
## Usage: sillage:eslint
## Example: "ddev sillage:eslint"

if [ ! -d "/var/www/html/web/themes/custom/sillage" ]; then
    echo "Error: Theme 'sillage' not found in web/themes/custom/"
    exit 1
fi
cd /var/www/html/web/themes/custom/sillage || exit
npm run eslint
