#!/bin/bash

## Description: Apply stylelint to the Sillage theme.
## Usage: sillage:stylelint
## Example: "ddev sillage:stylelint"


if [ ! -d "/var/www/html/web/themes/custom/sillage" ]; then
    echo "Error: Theme 'sillage' not found in web/themes/custom/"
    exit 1
fi
cd /var/www/html/web/themes/custom/sillage || exit
npm run stylelint
